% use matlab to modify the data generated by octave(bgs_seven.m);
load bgs_seven_octave.mat;
% model,train,label
seven=train{1};
[height,width,channel]=size(seven);
channel=channel-4;

M=length(model);
for i=M:-1:1
   seven=model{i};
   gray=seven(:,:,channel+1);
   [dx,dy]=imgradientxy(gray);
   seven(:,:,channel+1)=dx;
   seven(:,:,channel+2)=dy;
   model{i}=seven;
end

N=length(train);
for i=N:-1:1
   seven=train{i};
   gray=seven(:,:,channel+1);
   [dx,dy]=imgradientxy(gray);
   seven(:,:,channel+1)=dx;
   seven(:,:,channel+2)=dy;
   train{i}=seven;
end

save bgs_seven_step2.mat model train label;